name: down_yt
description: a youtube downloader application
version: 0.0.1-alpha
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.6

dependencies:
  # Android Path


  # Notification Manager
  awesome_notifications: ^0.9.3+1

  # Dart State Management
  bloc: ^8.1.4

  # Built List
  built_collection: ^5.1.1

  # Functional Programming
  dartz: any

  # HTTP Requests
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1

  # Equal data and type
  equatable: ^2.0.5

  # Flutter SDK
  flutter:
    sdk: flutter

  # Flutter State Management
  flutter_bloc: ^8.1.6

  # Video Encoding and Rendering
  ffmpeg_kit_flutter: ^6.0.3

  # flutter_vlc_player: ^7.1.5
  # State Management
  get_it: ^7.7.0

# Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Checks internet Connections
  internet_connection_checker: ^2.0.0


  # Mini Player
  miniplayer: ^1.0.1

  # Open File
  open_file: ^3.5.3

  # Gets the paths
  path_provider: ^2.1.4

  path_provider_android: ^2.2.10

  # Gets Permissions on Android devices
  permission_handler: ^11.3.1
  pip_view: ^0.9.7
  piped_client: any
  pod_player: ^0.2.2
  share_plus: ^10.0.2


  # Youtube API and Downloadable
  youtube_explode_dart: ^2.2.1

  # Flutter Youtube Player
  # youtube_player_flutter: ^8.1.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  hive_generator: any
  #  build_runner: ^2.3.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
